// Regenerates the "The work" table in README.md from src/data/projects.ts,
// between the two marker comments, so the README cannot describe a study
// differently from the site. It follows the same rule llms.txt and resume.txt
// already follow: if a surface can be generated from the data, it is.
//
//   npm run readme
//
// Only the marked block changes; everything else in the README is hand-written
// and left alone. The data is bundled with esbuild the way casestudy-md.mjs
// does it, with images stubbed, so no Vite is needed.

import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";

const README = "README.md";
const START = "<!-- work-table:start -->";
const END = "<!-- work-table:end -->";

const imgStub = {
  name: "img-stub",
  setup(b) {
    b.onResolve({ filter: /\.(jpe?g|png|webp|svg|gif)(\?.*)?$/ }, (a) => ({ path: a.path, namespace: "img" }));
    b.onLoad({ filter: /.*/, namespace: "img" }, (a) => ({
      contents: `export default ${JSON.stringify(a.path)}`,
      loader: "js",
    }));
  },
};

const bundle = await build({
  stdin: {
    contents: 'export { projects } from "./src/data/projects"; export { SITE_URL } from "./src/data/routes";',
    resolveDir: process.cwd(),
    loader: "ts",
  },
  bundle: true,
  write: false,
  format: "esm",
  platform: "node",
  plugins: [imgStub],
});
const { projects, SITE_URL } = await import(
  "data:text/javascript;base64," + Buffer.from(bundle.outputFiles[0].text).toString("base64")
);

// A pipe inside a cell would split the table; there are none today, but a
// tagline is free text.
const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();

const rows = [...projects]
  .sort((a, b) => a.featuredOrder - b.featuredOrder)
  .map((p) => `| **[${cell(p.title)}](${SITE_URL}/work/${p.slug})** | ${cell(p.tagline)} | ${cell(p.role)} | ${cell(p.status)} |`);

const table = [
  START,
  "<!-- Generated by scripts/readme-work.mjs from src/data/projects.ts. Edit the data, then run `npm run readme`. -->",
  "",
  "| Case study | What it was | My role | Status |",
  "| --- | --- | --- | --- |",
  ...rows,
  "",
  END,
].join("\n");

const readme = readFileSync(README, "utf8");
const start = readme.indexOf(START);
const end = readme.indexOf(END);
if (start === -1 || end === -1 || end < start) {
  console.error(`README.md needs both markers, ${START} before ${END}.`);
  process.exit(1);
}

const next = readme.slice(0, start) + table + readme.slice(end + END.length);
if (next === readme) {
  console.log("README.md work table already up to date.");
} else {
  writeFileSync(README, next);
  console.log(`README.md work table regenerated (${rows.length} studies).`);
}
